/*
 * generator.h
 *
 *  Created on: 08.12.2011
 *      Author: marscher
 */

#ifndef GEOM_GENERATOR_H_
#define GEOM_GENERATOR_H_

#include "common_typedefs.h"
#include "util/rotation_matrix.h"

namespace ug {
namespace tkd {

/**
 * generates domain decomposition of tetrakaidecahedron.
 * After calling createDomain() you can get the positions and indices
 * of the created geometries to create a Grid object
 */
class TKDGeometryGenerator {

public:
	void createGeometry();

	/**
	 * creates an empty geometry generator. WARNING: this is not yet usable!
	 * use setBaseEdgeLength(), setDiameter(), setHeight() and setLipidThickness()
	 */
	TKDGeometryGenerator();

	/**
	 * @param height
	 * @param baseEdgeLength
	 * @param diameter
	 * @param d_lipid
	 */
	TKDGeometryGenerator(number a, number w, number height, bool createLipid = true,
			number d_lipid = 1);

	/**
	 * should lipid geometry be created?
	 */
	bool createLipid() const;

	void setCreateLipid(bool);

	/**
	 * gets volume of given subset
	 */
	number getVolume(int subset = LIPID) const;

	/**
	 * calculates volume for given geometrical parameters
	 */
	static number getVolume(number a, number s, number h);

	/**
	 * gets surface for given subset
	 */
	number getSurface(int subset = LIPID) const;

	/**
	 * calculates surface for given geometrical parameters
	 */
	static number getSurface(number a, number s, number h);

	const IndexArray& getIndices() const;
	const CoordsArray& getPositions() const;

	number getHeight() const;
	number getOverlap() const;

	// setter
	void setHeight(number height);
	void setBaseEdgeLength(number a);
	void setDiameter(number w);
	void setLipidThickness(number d);
	void setGeometricParams(number a, number w, number h, number d_lipid);

protected:
	/**
	 * number of vertices of used solid figures
	 */
	enum SolidFigures {
		Tetrahedron = 4, Pyramid = 5, Prism = 6, Hexahedron = 8
	};

	bool b_createLipid;

	// height of one third of tkd : h = 1/3 * h_tkd
	number h_corneocyte;
	// base edge length of central hexahedron
	number a_corneocyte;
	// diameter
	number w_corneocyte;
	number s_corneocyte;
	// thickness of lipid matrix
	number d_lipid;
	// base edge length of lipid matrix
	number a_lipid;
	// height of 1/3 of lipid matrix
	number h_lipid;
	// quantity s, overlap of two aligned tkds with lipid matrix
	number s_lipid;
	number w_lipid;

	/**
	 * stores coordinates of points
	 */
	CoordsArray posOut;

	/**
	 * stores indices for points
	 */
	IndexArray indsOut;

	// matrix used to rotate all geometric objects around z axis
	RotationMatrix R;

	// global index which is incremented for all vertices generated by this instance
	size_t index;

	/**
	 * inits base geometric parameters
	 */
	void initGeometricParams();

	void initLipidGeometric();

	void updateOverlap(int subset);

	void setLipidBaseEdgeLength();
	void setLipidHeight();
	void setLipidDiameter();
	void setLipidParameters();

	void createCorneocyte(const vector3&);
	void createLipidMatrix(const vector3&, const number rotationOffset = 0,
			bool bottom = false);

	/**
	 *	creates the upper part of tkd (symmetric to bottom part!)
	 */
	void createCorneocyteTop(const vector3& offset,
			const number rotationOffset = 0, bool bottom = false);

	/**
	 * creates middle part with given offset
	 */
	void createCorneocyteMiddle(const vector3& offset);

	/**
	 * pushes posIn into global posOut reference and creates
	 * indices for each vertex which are pushed into global indsOut reference
	 */
	void createGeometricObject(const CoordsArray& posIn);

	void flipOrientationPrism(CoordsArray& prismPos) const;
	void flipOrientationPyramid(CoordsArray& pyramidPos) const;
	void flipOrientationTetrahedron(CoordsArray& tetrahedronPos) const;
	void flipOrientationHexahedron(CoordsArray& hexaPos) const;

	///// segments of top and bottom
	CoordsArray obenInnen;
	// G(Ki -> ObenAussenPr)
	CoordsArray obenAussenPrism;

	CoordsArray obenAussenPr_rightTetrahedron;
	CoordsArray obenAussenPr_leftTetrahedron;
	CoordsArray obenAussenPr2T_prism;

	///// segments of middle part
	// outer prism
	CoordsArray mitteAussenP1;
	// inner prism
	CoordsArray mitteAussenP2;

	// below obenAussenPr_rightTetrahedron
	CoordsArray mitteAussenH2Pr_tetrahedron;
	CoordsArray mitteAussenH2Pr_pyramid;

	CoordsArray mitteAussen2PrH_tetrahedron;
	CoordsArray mitteAussen2PrH_pyramid;

	// below obenAussenPrism
	CoordsArray mitteAussenHexahedron;

	// lipid matrix
	/// lipid hexagon
	CoordsArray obenInnenPrismL;
	CoordsArray obenAussenPrismL;
	CoordsArray obenAussen_leftPrismL;
	CoordsArray obenAussen_rightPrismL;
	CoordsArray upperHexahedronL;
	CoordsArray bottomOuterHexahedronL;
	CoordsArray bottomLeftPrismL;
	CoordsArray bottomRightPrismL;

	// lipid side quad
	CoordsArray sideQuad;

	const static vector3 origin;
};

} //end of namespace tkd
}// end of namespace ug
#endif /* GEOM_GENERATOR_H_ */
